# -*- coding: utf-8 -*-
"""andypon.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OHHqgWlU2bCxMTWnMePsWFCc0C1sbyZD
"""

import time

ex_NONE = "None"
ex_LIGHT = "Light"
ex_MODERATE = "Moderate"
ex_HEAVY = "Heavy"

validation_ex = {
    ex_NONE,
    ex_LIGHT,
    ex_MODERATE,
    ex_HEAVY
}

def evaluate_wound(area, pain, exudate):
    area = float(area)
    pain = int(pain)
    exudate = exudate.capitalize()

    #Critical警示判斷條件
    if area > 5 or pain > 7 or exudate == ex_HEAVY:
        return (
            "警示 (Critical)",
            "傷口狀況嚴重，具進一步感染風險，建議立即尋求專業醫療人員介入。"
        )

    #Good良好判斷條件
    if area < 2 and pain < 3 and exudate in {ex_NONE, ex_LIGHT}:
        return (
            "良好 (Good)",
            "傷口癒合狀況理想，請持續保持傷口清潔乾燥，根據醫囑繼續照護即可。"
        )

    #Warning需注意判斷條件
    return (
        "需注意 (Warning)",
        "傷口狀況仍需密切觀察，請增加換藥頻率，若症狀加劇請儘速回診。"
    )


def Startup():
    print("歡迎使用工研院服科中心【傷口癒合狀態提示小幫手】", end="")

    # 增加程式運行互動感
    for _ in range(5):
        time.sleep(0.3)
        print(".", end="", flush=True)

    time.sleep(0.5)
    print("\n系統啟動完成！")

def run_test_cases():
    print("\n" + "-" * 30)
    print("正在執行內建測試資料...")
    print("-" * 30)

    test_data = [
        {"area": 1.5, "pain": 1, "exudate": "None"},
        {"area": 6.0, "pain": 2, "exudate": "Light"},
        {"area": 3.0, "pain": 5, "exudate": "Moderate"},
        {"area": 1.0, "pain": 8, "exudate": "None"},
    ]

    for i, data in enumerate(test_data, 1):
        # note：Function 直接回傳 (status, advice)
        status, advice = evaluate_wound(data['area'], data['pain'], data['exudate'])
        print(f"案例 {i}: Area={data['area']}, Pain={data['pain']}, Exudate={data['exudate']}")
        print(f"評估結果: {status}")
        print(f"照護建議: {advice}\n")

    print("測試資料執行完畢，程式結束。")

def get_user_input():
    print("\n" + "-" * 40)
    print("進入手動輸入模式 ")
    print("-" * 40)

    while True:
        try:
            print("\n>>> 請輸入您的照護相關資料：")
            print("\n>>> 請輸入您的傷口面積 (cm2)，並確保測量面積>=0：")
            area_str = input("1. 傷口面積 (cm2): ")
            pain_str = input("2. 疼痛等級 (0-10): ")
            print("3. 滲液量 (None, Light, Moderate, Heavy)")
            exudate_str = input("   輸入（大小寫不拘）: ")

            # 輸入資料再度確認
            print("\n" + "-"*15 + " 使用者輸入資料確認 " + "-"*15)
            print(f"  • 傷口面積: {area_str}")
            print(f"  • 疼痛等級: {pain_str}")
            print(f"  • 滲液量: {exudate_str}")

            confirm = input("\n請確認以上輸入資料正確與否？(y/n): ")
            if confirm.lower() == 'y':
              try:
                    #將字串轉為數字進行檢查
                    check_area = float(area_str)
                    check_pain = int(pain_str)
                    check_exudate_str = exudate_str.capitalize()

                    #檢查邏輯：面積不能為負
                    if check_area < 0:
                        print("\n 【錯誤訊息】：傷口面積不能為負數！請重新輸入。")
                        time.sleep(2)
                        continue

                    #print("here")
                    #檢查邏輯：疼痛範圍輸入
                    if check_pain < 0 or check_pain > 10:
                        print("\n 【錯誤訊息】：疼痛等級必須在 0 到 10 之間！請重新輸入。")
                        time.sleep(2)
                        continue

                    if check_exudate_str not in validation_ex:
                        print("\n 【錯誤訊息】：滲液量輸入必須為 (None, Light, Moderate, Heavy)其中一類別")
                        time.sleep(2)
                        continue


              except ValueError:              #檢查邏輯：其他報錯，如輸入無法轉成數字
                print("\n 數入格式錯誤：面積與疼痛等級必須是『數字』！麻煩請重新輸入。")
                time.sleep(2)
                continue
              #print("使用者核對輸入資料y")


            else:
              print(">>> 資料已取消，請重新輸入...\n")
              continue


            status, advice = evaluate_wound(area_str, pain_str, exudate_str)

            print("\n" + "="*20 + " 評估報告 " + "="*20)
            print(f"狀態: {status}")
            print(f"建議: {advice}")
            print("="*49)


            again = input("\n還需要輸入下一筆資料嗎？(y/n): ")
            if again.lower() != 'y':
                time.sleep(1)
                print("手動輸入模式結束\n")
                break

        except ValueError:
            print("\n 輸入格式錯誤！請確保數值欄位輸入正確的數字。")
        except Exception as e:
            print(f"\n 發生未預期的錯誤: {e}")

if __name__ == "__main__":
    Startup()
    time.sleep(1)
    while True:
      print("\n請選擇運行程式模式：")
      print("1. 執行內建測試資料來運行程式")
      print("2. 手動輸入資料提供照護建議")

      choice = input("請輸入“純數字”選項 (1 或 2): ")

      if choice == '1':
          run_test_cases()
          break
      elif choice == '2':
          get_user_input()
          break
      else:
          time.sleep(1)
          print("\n輸入錯誤，麻煩重新在1或2中再選擇一次～")
          time.sleep(1)
    print("\n謝謝您使用工研院【傷口癒合狀態提示小幫手】，祝您早日康復！")

